# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kocheng' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for kocheng
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'Moya', '~> 14.0'

end
